- -not_implemented_func_hack.patch   comment out ((registry)|(kdb))[GS]etComment to avoid:
  /lib/libregistry.so: undefined reference to `kdbGetComment'
  /lib/libregistry.so: undefined reference to `kdbSetComment'
  collect2: ld returned 1 exit status
  make[1]: *** [regedit] Error 1

  kdb[GS]etComment are declared but not defined.

Changed files:
    elektra-not_implemented_func_hack.patch -> 1.1